package com.unsw.web.entity;
// Generated 2019-10-17 16:45:33 by Hibernate Tools 5.2.12.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * SaveDetailId generated by hbm2java
 */
@Embeddable
public class SaveDetailId implements java.io.Serializable {

	private int recipeId;
	private int userId;

	public SaveDetailId() {
	}

	public SaveDetailId(int recipeId, int userId) {
		this.recipeId = recipeId;
		this.userId = userId;
	}

	@Column(name = "recipe_id", nullable = false)
	public int getRecipeId() {
		return this.recipeId;
	}

	public void setRecipeId(int recipeId) {
		this.recipeId = recipeId;
	}

	@Column(name = "user_id", nullable = false)
	public int getUserId() {
		return this.userId;
	}

	public void setUserId(int userId) {
		this.userId = userId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof SaveDetailId))
			return false;
		SaveDetailId castOther = (SaveDetailId) other;

		return (this.getRecipeId() == castOther.getRecipeId()) && (this.getUserId() == castOther.getUserId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getRecipeId();
		result = 37 * result + this.getUserId();
		return result;
	}

}
