package com.unsw.web.entity;
// Generated 2019-10-14 18:17:54 by Hibernate Tools 5.3.10.Final

/**
 * HostSummary generated by hbm2java
 */
public class HostSummary implements java.io.Serializable {

	private HostSummaryId id;

	public HostSummary() {
	}

	public HostSummary(HostSummaryId id) {
		this.id = id;
	}

	public HostSummaryId getId() {
		return this.id;
	}

	public void setId(HostSummaryId id) {
		this.id = id;
	}

}
