package com.unsw.web.entity;
// Generated 2019-10-14 18:17:54 by Hibernate Tools 5.3.10.Final

/**
 * HostSummaryByFileIoType generated by hbm2java
 */
public class HostSummaryByFileIoType implements java.io.Serializable {

	private HostSummaryByFileIoTypeId id;

	public HostSummaryByFileIoType() {
	}

	public HostSummaryByFileIoType(HostSummaryByFileIoTypeId id) {
		this.id = id;
	}

	public HostSummaryByFileIoTypeId getId() {
		return this.id;
	}

	public void setId(HostSummaryByFileIoTypeId id) {
		this.id = id;
	}

}
