package com.unsw.web.entity;
// Generated 2019-10-14 18:17:54 by Hibernate Tools 5.3.10.Final

/**
 * HostSummaryByStages generated by hbm2java
 */
public class HostSummaryByStages implements java.io.Serializable {

	private HostSummaryByStagesId id;

	public HostSummaryByStages() {
	}

	public HostSummaryByStages(HostSummaryByStagesId id) {
		this.id = id;
	}

	public HostSummaryByStagesId getId() {
		return this.id;
	}

	public void setId(HostSummaryByStagesId id) {
		this.id = id;
	}

}
