package com.unsw.web.entity;
// Generated 2019-10-14 18:17:54 by Hibernate Tools 5.3.10.Final

/**
 * IoByThreadByLatency generated by hbm2java
 */
public class IoByThreadByLatency implements java.io.Serializable {

	private IoByThreadByLatencyId id;

	public IoByThreadByLatency() {
	}

	public IoByThreadByLatency(IoByThreadByLatencyId id) {
		this.id = id;
	}

	public IoByThreadByLatencyId getId() {
		return this.id;
	}

	public void setId(IoByThreadByLatencyId id) {
		this.id = id;
	}

}
