package com.unsw.web.entity;
// Generated 2019-10-14 18:17:54 by Hibernate Tools 5.3.10.Final

/**
 * IoGlobalByWaitByBytes generated by hbm2java
 */
public class IoGlobalByWaitByBytes implements java.io.Serializable {

	private IoGlobalByWaitByBytesId id;

	public IoGlobalByWaitByBytes() {
	}

	public IoGlobalByWaitByBytes(IoGlobalByWaitByBytesId id) {
		this.id = id;
	}

	public IoGlobalByWaitByBytesId getId() {
		return this.id;
	}

	public void setId(IoGlobalByWaitByBytesId id) {
		this.id = id;
	}

}
