package com.unsw.web.entity;
// Generated 2019-10-14 18:17:54 by Hibernate Tools 5.3.10.Final

/**
 * IoGlobalByFileByLatencyId generated by hbm2java
 */
public class IoGlobalByFileByLatencyId implements java.io.Serializable {

	private String file;
	private long total;
	private String totalLatency;
	private long countRead;
	private String readLatency;
	private long countWrite;
	private String writeLatency;
	private long countMisc;
	private String miscLatency;

	public IoGlobalByFileByLatencyId() {
	}

	public IoGlobalByFileByLatencyId(long total, long countRead, long countWrite, long countMisc) {
		this.total = total;
		this.countRead = countRead;
		this.countWrite = countWrite;
		this.countMisc = countMisc;
	}

	public IoGlobalByFileByLatencyId(String file, long total, String totalLatency, long countRead, String readLatency,
			long countWrite, String writeLatency, long countMisc, String miscLatency) {
		this.file = file;
		this.total = total;
		this.totalLatency = totalLatency;
		this.countRead = countRead;
		this.readLatency = readLatency;
		this.countWrite = countWrite;
		this.writeLatency = writeLatency;
		this.countMisc = countMisc;
		this.miscLatency = miscLatency;
	}

	public String getFile() {
		return this.file;
	}

	public void setFile(String file) {
		this.file = file;
	}

	public long getTotal() {
		return this.total;
	}

	public void setTotal(long total) {
		this.total = total;
	}

	public String getTotalLatency() {
		return this.totalLatency;
	}

	public void setTotalLatency(String totalLatency) {
		this.totalLatency = totalLatency;
	}

	public long getCountRead() {
		return this.countRead;
	}

	public void setCountRead(long countRead) {
		this.countRead = countRead;
	}

	public String getReadLatency() {
		return this.readLatency;
	}

	public void setReadLatency(String readLatency) {
		this.readLatency = readLatency;
	}

	public long getCountWrite() {
		return this.countWrite;
	}

	public void setCountWrite(long countWrite) {
		this.countWrite = countWrite;
	}

	public String getWriteLatency() {
		return this.writeLatency;
	}

	public void setWriteLatency(String writeLatency) {
		this.writeLatency = writeLatency;
	}

	public long getCountMisc() {
		return this.countMisc;
	}

	public void setCountMisc(long countMisc) {
		this.countMisc = countMisc;
	}

	public String getMiscLatency() {
		return this.miscLatency;
	}

	public void setMiscLatency(String miscLatency) {
		this.miscLatency = miscLatency;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof IoGlobalByFileByLatencyId))
			return false;
		IoGlobalByFileByLatencyId castOther = (IoGlobalByFileByLatencyId) other;

		return ((this.getFile() == castOther.getFile()) || (this.getFile() != null && castOther.getFile() != null
				&& this.getFile().equals(castOther.getFile())))
				&& (this.getTotal() == castOther.getTotal())
				&& ((this.getTotalLatency() == castOther.getTotalLatency())
						|| (this.getTotalLatency() != null && castOther.getTotalLatency() != null
								&& this.getTotalLatency().equals(castOther.getTotalLatency())))
				&& (this.getCountRead() == castOther.getCountRead())
				&& ((this.getReadLatency() == castOther.getReadLatency())
						|| (this.getReadLatency() != null && castOther.getReadLatency() != null
								&& this.getReadLatency().equals(castOther.getReadLatency())))
				&& (this.getCountWrite() == castOther.getCountWrite())
				&& ((this.getWriteLatency() == castOther.getWriteLatency())
						|| (this.getWriteLatency() != null && castOther.getWriteLatency() != null
								&& this.getWriteLatency().equals(castOther.getWriteLatency())))
				&& (this.getCountMisc() == castOther.getCountMisc())
				&& ((this.getMiscLatency() == castOther.getMiscLatency())
						|| (this.getMiscLatency() != null && castOther.getMiscLatency() != null
								&& this.getMiscLatency().equals(castOther.getMiscLatency())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getFile() == null ? 0 : this.getFile().hashCode());
		result = 37 * result + (int) this.getTotal();
		result = 37 * result + (getTotalLatency() == null ? 0 : this.getTotalLatency().hashCode());
		result = 37 * result + (int) this.getCountRead();
		result = 37 * result + (getReadLatency() == null ? 0 : this.getReadLatency().hashCode());
		result = 37 * result + (int) this.getCountWrite();
		result = 37 * result + (getWriteLatency() == null ? 0 : this.getWriteLatency().hashCode());
		result = 37 * result + (int) this.getCountMisc();
		result = 37 * result + (getMiscLatency() == null ? 0 : this.getMiscLatency().hashCode());
		return result;
	}

}
