package com.unsw.web.entity;
// Generated 2019-10-14 18:17:54 by Hibernate Tools 5.3.10.Final

/**
 * LatestFileIo generated by hbm2java
 */
public class LatestFileIo implements java.io.Serializable {

	private LatestFileIoId id;

	public LatestFileIo() {
	}

	public LatestFileIo(LatestFileIoId id) {
		this.id = id;
	}

	public LatestFileIoId getId() {
		return this.id;
	}

	public void setId(LatestFileIoId id) {
		this.id = id;
	}

}
