package com.unsw.web.entity;
// Generated 2019-10-14 18:17:54 by Hibernate Tools 5.3.10.Final

/**
 * MemoryGlobalTotal generated by hbm2java
 */
public class MemoryGlobalTotal implements java.io.Serializable {

	private String totalAllocated;

	public MemoryGlobalTotal() {
	}

	public MemoryGlobalTotal(String totalAllocated) {
		this.totalAllocated = totalAllocated;
	}

	public String getTotalAllocated() {
		return this.totalAllocated;
	}

	public void setTotalAllocated(String totalAllocated) {
		this.totalAllocated = totalAllocated;
	}

}
