package com.unsw.web.entity;
// Generated 2019-10-14 18:17:54 by Hibernate Tools 5.3.10.Final

/**
 * MemoryByHostByCurrentBytes generated by hbm2java
 */
public class MemoryByHostByCurrentBytes implements java.io.Serializable {

	private MemoryByHostByCurrentBytesId id;

	public MemoryByHostByCurrentBytes() {
	}

	public MemoryByHostByCurrentBytes(MemoryByHostByCurrentBytesId id) {
		this.id = id;
	}

	public MemoryByHostByCurrentBytesId getId() {
		return this.id;
	}

	public void setId(MemoryByHostByCurrentBytesId id) {
		this.id = id;
	}

}
