package com.unsw.web.entity;
// Generated 2019-10-14 18:17:54 by Hibernate Tools 5.3.10.Final

/**
 * Metrics generated by hbm2java
 */
public class Metrics implements java.io.Serializable {

	private MetricsId id;

	public Metrics() {
	}

	public Metrics(MetricsId id) {
		this.id = id;
	}

	public MetricsId getId() {
		return this.id;
	}

	public void setId(MetricsId id) {
		this.id = id;
	}

}
