package com.unsw.web.entity;
// Generated 2019-10-14 18:17:54 by Hibernate Tools 5.3.10.Final

/**
 * OrderDetail generated by hbm2java
 */
public class OrderDetail implements java.io.Serializable {

	private OrderDetailId id;
	private Recipe recipe;
	private RecipeOrder recipeOrder;

	public OrderDetail() {
	}

	public OrderDetail(OrderDetailId id) {
		this.id = id;
	}

	public OrderDetail(OrderDetailId id, Recipe recipe, RecipeOrder recipeOrder) {
		this.id = id;
		this.recipe = recipe;
		this.recipeOrder = recipeOrder;
	}

	public OrderDetailId getId() {
		return this.id;
	}

	public void setId(OrderDetailId id) {
		this.id = id;
	}

	public Recipe getRecipe() {
		return this.recipe;
	}

	public void setRecipe(Recipe recipe) {
		this.recipe = recipe;
	}

	public RecipeOrder getRecipeOrder() {
		return this.recipeOrder;
	}

	public void setRecipeOrder(RecipeOrder recipeOrder) {
		this.recipeOrder = recipeOrder;
	}

}
