package com.unsw.web.entity;
// Generated 2019-10-14 18:17:54 by Hibernate Tools 5.3.10.Final

/**
 * PsCheckLostInstrumentationId generated by hbm2java
 */
public class PsCheckLostInstrumentationId implements java.io.Serializable {

	private String variableName;
	private String variableValue;

	public PsCheckLostInstrumentationId() {
	}

	public PsCheckLostInstrumentationId(String variableName) {
		this.variableName = variableName;
	}

	public PsCheckLostInstrumentationId(String variableName, String variableValue) {
		this.variableName = variableName;
		this.variableValue = variableValue;
	}

	public String getVariableName() {
		return this.variableName;
	}

	public void setVariableName(String variableName) {
		this.variableName = variableName;
	}

	public String getVariableValue() {
		return this.variableValue;
	}

	public void setVariableValue(String variableValue) {
		this.variableValue = variableValue;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof PsCheckLostInstrumentationId))
			return false;
		PsCheckLostInstrumentationId castOther = (PsCheckLostInstrumentationId) other;

		return ((this.getVariableName() == castOther.getVariableName()) || (this.getVariableName() != null
				&& castOther.getVariableName() != null && this.getVariableName().equals(castOther.getVariableName())))
				&& ((this.getVariableValue() == castOther.getVariableValue())
						|| (this.getVariableValue() != null && castOther.getVariableValue() != null
								&& this.getVariableValue().equals(castOther.getVariableValue())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getVariableName() == null ? 0 : this.getVariableName().hashCode());
		result = 37 * result + (getVariableValue() == null ? 0 : this.getVariableValue().hashCode());
		return result;
	}

}
