package com.unsw.web.entity;
// Generated 2019-10-14 18:17:54 by Hibernate Tools 5.3.10.Final

/**
 * SchemaTableStatisticsWithBuffer generated by hbm2java
 */
public class SchemaTableStatisticsWithBuffer implements java.io.Serializable {

	private SchemaTableStatisticsWithBufferId id;

	public SchemaTableStatisticsWithBuffer() {
	}

	public SchemaTableStatisticsWithBuffer(SchemaTableStatisticsWithBufferId id) {
		this.id = id;
	}

	public SchemaTableStatisticsWithBufferId getId() {
		return this.id;
	}

	public void setId(SchemaTableStatisticsWithBufferId id) {
		this.id = id;
	}

}
