package com.unsw.web.entity;
// Generated 2019-10-14 18:17:54 by Hibernate Tools 5.3.10.Final

/**
 * SchemaIndexStatistics generated by hbm2java
 */
public class SchemaIndexStatistics implements java.io.Serializable {

	private SchemaIndexStatisticsId id;

	public SchemaIndexStatistics() {
	}

	public SchemaIndexStatistics(SchemaIndexStatisticsId id) {
		this.id = id;
	}

	public SchemaIndexStatisticsId getId() {
		return this.id;
	}

	public void setId(SchemaIndexStatisticsId id) {
		this.id = id;
	}

}
