package com.unsw.web.entity;
// Generated 2019-10-14 18:17:54 by Hibernate Tools 5.3.10.Final

/**
 * SchemaRedundantIndexes generated by hbm2java
 */
public class SchemaRedundantIndexes implements java.io.Serializable {

	private SchemaRedundantIndexesId id;

	public SchemaRedundantIndexes() {
	}

	public SchemaRedundantIndexes(SchemaRedundantIndexesId id) {
		this.id = id;
	}

	public SchemaRedundantIndexesId getId() {
		return this.id;
	}

	public void setId(SchemaRedundantIndexesId id) {
		this.id = id;
	}

}
