package com.unsw.web.entity;
// Generated 2019-10-14 18:17:54 by Hibernate Tools 5.3.10.Final

import java.math.BigInteger;

/**
 * SchemaTableStatisticsWithBufferId generated by hbm2java
 */
public class SchemaTableStatisticsWithBufferId implements java.io.Serializable {

	private String tableSchema;
	private String tableName;
	private long rowsFetched;
	private String fetchLatency;
	private long rowsInserted;
	private String insertLatency;
	private long rowsUpdated;
	private String updateLatency;
	private long rowsDeleted;
	private String deleteLatency;
	private BigInteger ioReadRequests;
	private String ioRead;
	private String ioReadLatency;
	private BigInteger ioWriteRequests;
	private String ioWrite;
	private String ioWriteLatency;
	private BigInteger ioMiscRequests;
	private String ioMiscLatency;
	private String innodbBufferAllocated;
	private String innodbBufferData;
	private String innodbBufferFree;
	private Long innodbBufferPages;
	private Long innodbBufferPagesHashed;
	private Long innodbBufferPagesOld;
	private BigInteger innodbBufferRowsCached;

	public SchemaTableStatisticsWithBufferId() {
	}

	public SchemaTableStatisticsWithBufferId(long rowsFetched, long rowsInserted, long rowsUpdated, long rowsDeleted) {
		this.rowsFetched = rowsFetched;
		this.rowsInserted = rowsInserted;
		this.rowsUpdated = rowsUpdated;
		this.rowsDeleted = rowsDeleted;
	}

	public SchemaTableStatisticsWithBufferId(String tableSchema, String tableName, long rowsFetched,
			String fetchLatency, long rowsInserted, String insertLatency, long rowsUpdated, String updateLatency,
			long rowsDeleted, String deleteLatency, BigInteger ioReadRequests, String ioRead, String ioReadLatency,
			BigInteger ioWriteRequests, String ioWrite, String ioWriteLatency, BigInteger ioMiscRequests,
			String ioMiscLatency, String innodbBufferAllocated, String innodbBufferData, String innodbBufferFree,
			Long innodbBufferPages, Long innodbBufferPagesHashed, Long innodbBufferPagesOld,
			BigInteger innodbBufferRowsCached) {
		this.tableSchema = tableSchema;
		this.tableName = tableName;
		this.rowsFetched = rowsFetched;
		this.fetchLatency = fetchLatency;
		this.rowsInserted = rowsInserted;
		this.insertLatency = insertLatency;
		this.rowsUpdated = rowsUpdated;
		this.updateLatency = updateLatency;
		this.rowsDeleted = rowsDeleted;
		this.deleteLatency = deleteLatency;
		this.ioReadRequests = ioReadRequests;
		this.ioRead = ioRead;
		this.ioReadLatency = ioReadLatency;
		this.ioWriteRequests = ioWriteRequests;
		this.ioWrite = ioWrite;
		this.ioWriteLatency = ioWriteLatency;
		this.ioMiscRequests = ioMiscRequests;
		this.ioMiscLatency = ioMiscLatency;
		this.innodbBufferAllocated = innodbBufferAllocated;
		this.innodbBufferData = innodbBufferData;
		this.innodbBufferFree = innodbBufferFree;
		this.innodbBufferPages = innodbBufferPages;
		this.innodbBufferPagesHashed = innodbBufferPagesHashed;
		this.innodbBufferPagesOld = innodbBufferPagesOld;
		this.innodbBufferRowsCached = innodbBufferRowsCached;
	}

	public String getTableSchema() {
		return this.tableSchema;
	}

	public void setTableSchema(String tableSchema) {
		this.tableSchema = tableSchema;
	}

	public String getTableName() {
		return this.tableName;
	}

	public void setTableName(String tableName) {
		this.tableName = tableName;
	}

	public long getRowsFetched() {
		return this.rowsFetched;
	}

	public void setRowsFetched(long rowsFetched) {
		this.rowsFetched = rowsFetched;
	}

	public String getFetchLatency() {
		return this.fetchLatency;
	}

	public void setFetchLatency(String fetchLatency) {
		this.fetchLatency = fetchLatency;
	}

	public long getRowsInserted() {
		return this.rowsInserted;
	}

	public void setRowsInserted(long rowsInserted) {
		this.rowsInserted = rowsInserted;
	}

	public String getInsertLatency() {
		return this.insertLatency;
	}

	public void setInsertLatency(String insertLatency) {
		this.insertLatency = insertLatency;
	}

	public long getRowsUpdated() {
		return this.rowsUpdated;
	}

	public void setRowsUpdated(long rowsUpdated) {
		this.rowsUpdated = rowsUpdated;
	}

	public String getUpdateLatency() {
		return this.updateLatency;
	}

	public void setUpdateLatency(String updateLatency) {
		this.updateLatency = updateLatency;
	}

	public long getRowsDeleted() {
		return this.rowsDeleted;
	}

	public void setRowsDeleted(long rowsDeleted) {
		this.rowsDeleted = rowsDeleted;
	}

	public String getDeleteLatency() {
		return this.deleteLatency;
	}

	public void setDeleteLatency(String deleteLatency) {
		this.deleteLatency = deleteLatency;
	}

	public BigInteger getIoReadRequests() {
		return this.ioReadRequests;
	}

	public void setIoReadRequests(BigInteger ioReadRequests) {
		this.ioReadRequests = ioReadRequests;
	}

	public String getIoRead() {
		return this.ioRead;
	}

	public void setIoRead(String ioRead) {
		this.ioRead = ioRead;
	}

	public String getIoReadLatency() {
		return this.ioReadLatency;
	}

	public void setIoReadLatency(String ioReadLatency) {
		this.ioReadLatency = ioReadLatency;
	}

	public BigInteger getIoWriteRequests() {
		return this.ioWriteRequests;
	}

	public void setIoWriteRequests(BigInteger ioWriteRequests) {
		this.ioWriteRequests = ioWriteRequests;
	}

	public String getIoWrite() {
		return this.ioWrite;
	}

	public void setIoWrite(String ioWrite) {
		this.ioWrite = ioWrite;
	}

	public String getIoWriteLatency() {
		return this.ioWriteLatency;
	}

	public void setIoWriteLatency(String ioWriteLatency) {
		this.ioWriteLatency = ioWriteLatency;
	}

	public BigInteger getIoMiscRequests() {
		return this.ioMiscRequests;
	}

	public void setIoMiscRequests(BigInteger ioMiscRequests) {
		this.ioMiscRequests = ioMiscRequests;
	}

	public String getIoMiscLatency() {
		return this.ioMiscLatency;
	}

	public void setIoMiscLatency(String ioMiscLatency) {
		this.ioMiscLatency = ioMiscLatency;
	}

	public String getInnodbBufferAllocated() {
		return this.innodbBufferAllocated;
	}

	public void setInnodbBufferAllocated(String innodbBufferAllocated) {
		this.innodbBufferAllocated = innodbBufferAllocated;
	}

	public String getInnodbBufferData() {
		return this.innodbBufferData;
	}

	public void setInnodbBufferData(String innodbBufferData) {
		this.innodbBufferData = innodbBufferData;
	}

	public String getInnodbBufferFree() {
		return this.innodbBufferFree;
	}

	public void setInnodbBufferFree(String innodbBufferFree) {
		this.innodbBufferFree = innodbBufferFree;
	}

	public Long getInnodbBufferPages() {
		return this.innodbBufferPages;
	}

	public void setInnodbBufferPages(Long innodbBufferPages) {
		this.innodbBufferPages = innodbBufferPages;
	}

	public Long getInnodbBufferPagesHashed() {
		return this.innodbBufferPagesHashed;
	}

	public void setInnodbBufferPagesHashed(Long innodbBufferPagesHashed) {
		this.innodbBufferPagesHashed = innodbBufferPagesHashed;
	}

	public Long getInnodbBufferPagesOld() {
		return this.innodbBufferPagesOld;
	}

	public void setInnodbBufferPagesOld(Long innodbBufferPagesOld) {
		this.innodbBufferPagesOld = innodbBufferPagesOld;
	}

	public BigInteger getInnodbBufferRowsCached() {
		return this.innodbBufferRowsCached;
	}

	public void setInnodbBufferRowsCached(BigInteger innodbBufferRowsCached) {
		this.innodbBufferRowsCached = innodbBufferRowsCached;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof SchemaTableStatisticsWithBufferId))
			return false;
		SchemaTableStatisticsWithBufferId castOther = (SchemaTableStatisticsWithBufferId) other;

		return ((this.getTableSchema() == castOther.getTableSchema()) || (this.getTableSchema() != null
				&& castOther.getTableSchema() != null && this.getTableSchema().equals(castOther.getTableSchema())))
				&& ((this.getTableName() == castOther.getTableName()) || (this.getTableName() != null
						&& castOther.getTableName() != null && this.getTableName().equals(castOther.getTableName())))
				&& (this.getRowsFetched() == castOther.getRowsFetched())
				&& ((this.getFetchLatency() == castOther.getFetchLatency())
						|| (this.getFetchLatency() != null && castOther.getFetchLatency() != null
								&& this.getFetchLatency().equals(castOther.getFetchLatency())))
				&& (this.getRowsInserted() == castOther.getRowsInserted())
				&& ((this.getInsertLatency() == castOther.getInsertLatency())
						|| (this.getInsertLatency() != null && castOther.getInsertLatency() != null
								&& this.getInsertLatency().equals(castOther.getInsertLatency())))
				&& (this.getRowsUpdated() == castOther.getRowsUpdated())
				&& ((this.getUpdateLatency() == castOther.getUpdateLatency())
						|| (this.getUpdateLatency() != null && castOther.getUpdateLatency() != null
								&& this.getUpdateLatency().equals(castOther.getUpdateLatency())))
				&& (this.getRowsDeleted() == castOther.getRowsDeleted())
				&& ((this.getDeleteLatency() == castOther.getDeleteLatency())
						|| (this.getDeleteLatency() != null && castOther.getDeleteLatency() != null
								&& this.getDeleteLatency().equals(castOther.getDeleteLatency())))
				&& ((this.getIoReadRequests() == castOther.getIoReadRequests())
						|| (this.getIoReadRequests() != null && castOther.getIoReadRequests() != null
								&& this.getIoReadRequests().equals(castOther.getIoReadRequests())))
				&& ((this.getIoRead() == castOther.getIoRead()) || (this.getIoRead() != null
						&& castOther.getIoRead() != null && this.getIoRead().equals(castOther.getIoRead())))
				&& ((this.getIoReadLatency() == castOther.getIoReadLatency())
						|| (this.getIoReadLatency() != null && castOther.getIoReadLatency() != null
								&& this.getIoReadLatency().equals(castOther.getIoReadLatency())))
				&& ((this.getIoWriteRequests() == castOther.getIoWriteRequests())
						|| (this.getIoWriteRequests() != null && castOther.getIoWriteRequests() != null
								&& this.getIoWriteRequests().equals(castOther.getIoWriteRequests())))
				&& ((this.getIoWrite() == castOther.getIoWrite()) || (this.getIoWrite() != null
						&& castOther.getIoWrite() != null && this.getIoWrite().equals(castOther.getIoWrite())))
				&& ((this.getIoWriteLatency() == castOther.getIoWriteLatency())
						|| (this.getIoWriteLatency() != null && castOther.getIoWriteLatency() != null
								&& this.getIoWriteLatency().equals(castOther.getIoWriteLatency())))
				&& ((this.getIoMiscRequests() == castOther.getIoMiscRequests())
						|| (this.getIoMiscRequests() != null && castOther.getIoMiscRequests() != null
								&& this.getIoMiscRequests().equals(castOther.getIoMiscRequests())))
				&& ((this.getIoMiscLatency() == castOther.getIoMiscLatency())
						|| (this.getIoMiscLatency() != null && castOther.getIoMiscLatency() != null
								&& this.getIoMiscLatency().equals(castOther.getIoMiscLatency())))
				&& ((this.getInnodbBufferAllocated() == castOther.getInnodbBufferAllocated())
						|| (this.getInnodbBufferAllocated() != null && castOther.getInnodbBufferAllocated() != null
								&& this.getInnodbBufferAllocated().equals(castOther.getInnodbBufferAllocated())))
				&& ((this.getInnodbBufferData() == castOther.getInnodbBufferData())
						|| (this.getInnodbBufferData() != null && castOther.getInnodbBufferData() != null
								&& this.getInnodbBufferData().equals(castOther.getInnodbBufferData())))
				&& ((this.getInnodbBufferFree() == castOther.getInnodbBufferFree())
						|| (this.getInnodbBufferFree() != null && castOther.getInnodbBufferFree() != null
								&& this.getInnodbBufferFree().equals(castOther.getInnodbBufferFree())))
				&& ((this.getInnodbBufferPages() == castOther.getInnodbBufferPages())
						|| (this.getInnodbBufferPages() != null && castOther.getInnodbBufferPages() != null
								&& this.getInnodbBufferPages().equals(castOther.getInnodbBufferPages())))
				&& ((this.getInnodbBufferPagesHashed() == castOther.getInnodbBufferPagesHashed())
						|| (this.getInnodbBufferPagesHashed() != null && castOther.getInnodbBufferPagesHashed() != null
								&& this.getInnodbBufferPagesHashed().equals(castOther.getInnodbBufferPagesHashed())))
				&& ((this.getInnodbBufferPagesOld() == castOther.getInnodbBufferPagesOld())
						|| (this.getInnodbBufferPagesOld() != null && castOther.getInnodbBufferPagesOld() != null
								&& this.getInnodbBufferPagesOld().equals(castOther.getInnodbBufferPagesOld())))
				&& ((this.getInnodbBufferRowsCached() == castOther.getInnodbBufferRowsCached())
						|| (this.getInnodbBufferRowsCached() != null && castOther.getInnodbBufferRowsCached() != null
								&& this.getInnodbBufferRowsCached().equals(castOther.getInnodbBufferRowsCached())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getTableSchema() == null ? 0 : this.getTableSchema().hashCode());
		result = 37 * result + (getTableName() == null ? 0 : this.getTableName().hashCode());
		result = 37 * result + (int) this.getRowsFetched();
		result = 37 * result + (getFetchLatency() == null ? 0 : this.getFetchLatency().hashCode());
		result = 37 * result + (int) this.getRowsInserted();
		result = 37 * result + (getInsertLatency() == null ? 0 : this.getInsertLatency().hashCode());
		result = 37 * result + (int) this.getRowsUpdated();
		result = 37 * result + (getUpdateLatency() == null ? 0 : this.getUpdateLatency().hashCode());
		result = 37 * result + (int) this.getRowsDeleted();
		result = 37 * result + (getDeleteLatency() == null ? 0 : this.getDeleteLatency().hashCode());
		result = 37 * result + (getIoReadRequests() == null ? 0 : this.getIoReadRequests().hashCode());
		result = 37 * result + (getIoRead() == null ? 0 : this.getIoRead().hashCode());
		result = 37 * result + (getIoReadLatency() == null ? 0 : this.getIoReadLatency().hashCode());
		result = 37 * result + (getIoWriteRequests() == null ? 0 : this.getIoWriteRequests().hashCode());
		result = 37 * result + (getIoWrite() == null ? 0 : this.getIoWrite().hashCode());
		result = 37 * result + (getIoWriteLatency() == null ? 0 : this.getIoWriteLatency().hashCode());
		result = 37 * result + (getIoMiscRequests() == null ? 0 : this.getIoMiscRequests().hashCode());
		result = 37 * result + (getIoMiscLatency() == null ? 0 : this.getIoMiscLatency().hashCode());
		result = 37 * result + (getInnodbBufferAllocated() == null ? 0 : this.getInnodbBufferAllocated().hashCode());
		result = 37 * result + (getInnodbBufferData() == null ? 0 : this.getInnodbBufferData().hashCode());
		result = 37 * result + (getInnodbBufferFree() == null ? 0 : this.getInnodbBufferFree().hashCode());
		result = 37 * result + (getInnodbBufferPages() == null ? 0 : this.getInnodbBufferPages().hashCode());
		result = 37 * result
				+ (getInnodbBufferPagesHashed() == null ? 0 : this.getInnodbBufferPagesHashed().hashCode());
		result = 37 * result + (getInnodbBufferPagesOld() == null ? 0 : this.getInnodbBufferPagesOld().hashCode());
		result = 37 * result + (getInnodbBufferRowsCached() == null ? 0 : this.getInnodbBufferRowsCached().hashCode());
		return result;
	}

}
