package com.unsw.web.entity;
// Generated 2019-10-14 18:17:54 by Hibernate Tools 5.3.10.Final

/**
 * SchemaObjectOverview generated by hbm2java
 */
public class SchemaObjectOverview implements java.io.Serializable {

	private SchemaObjectOverviewId id;

	public SchemaObjectOverview() {
	}

	public SchemaObjectOverview(SchemaObjectOverviewId id) {
		this.id = id;
	}

	public SchemaObjectOverviewId getId() {
		return this.id;
	}

	public void setId(SchemaObjectOverviewId id) {
		this.id = id;
	}

}
