package com.unsw.web.entity;
// Generated 2019-10-14 18:17:54 by Hibernate Tools 5.3.10.Final

/**
 * SchemaTableLockWaits generated by hbm2java
 */
public class SchemaTableLockWaits implements java.io.Serializable {

	private SchemaTableLockWaitsId id;

	public SchemaTableLockWaits() {
	}

	public SchemaTableLockWaits(SchemaTableLockWaitsId id) {
		this.id = id;
	}

	public SchemaTableLockWaitsId getId() {
		return this.id;
	}

	public void setId(SchemaTableLockWaitsId id) {
		this.id = id;
	}

}
