package com.unsw.web.entity;
// Generated 2019-10-14 18:17:54 by Hibernate Tools 5.3.10.Final

/**
 * SchemaTablesWithFullTableScansId generated by hbm2java
 */
public class SchemaTablesWithFullTableScansId implements java.io.Serializable {

	private String objectSchema;
	private String objectName;
	private long rowsFullScanned;
	private String latency;

	public SchemaTablesWithFullTableScansId() {
	}

	public SchemaTablesWithFullTableScansId(long rowsFullScanned) {
		this.rowsFullScanned = rowsFullScanned;
	}

	public SchemaTablesWithFullTableScansId(String objectSchema, String objectName, long rowsFullScanned,
			String latency) {
		this.objectSchema = objectSchema;
		this.objectName = objectName;
		this.rowsFullScanned = rowsFullScanned;
		this.latency = latency;
	}

	public String getObjectSchema() {
		return this.objectSchema;
	}

	public void setObjectSchema(String objectSchema) {
		this.objectSchema = objectSchema;
	}

	public String getObjectName() {
		return this.objectName;
	}

	public void setObjectName(String objectName) {
		this.objectName = objectName;
	}

	public long getRowsFullScanned() {
		return this.rowsFullScanned;
	}

	public void setRowsFullScanned(long rowsFullScanned) {
		this.rowsFullScanned = rowsFullScanned;
	}

	public String getLatency() {
		return this.latency;
	}

	public void setLatency(String latency) {
		this.latency = latency;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof SchemaTablesWithFullTableScansId))
			return false;
		SchemaTablesWithFullTableScansId castOther = (SchemaTablesWithFullTableScansId) other;

		return ((this.getObjectSchema() == castOther.getObjectSchema()) || (this.getObjectSchema() != null
				&& castOther.getObjectSchema() != null && this.getObjectSchema().equals(castOther.getObjectSchema())))
				&& ((this.getObjectName() == castOther.getObjectName()) || (this.getObjectName() != null
						&& castOther.getObjectName() != null && this.getObjectName().equals(castOther.getObjectName())))
				&& (this.getRowsFullScanned() == castOther.getRowsFullScanned())
				&& ((this.getLatency() == castOther.getLatency()) || (this.getLatency() != null
						&& castOther.getLatency() != null && this.getLatency().equals(castOther.getLatency())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getObjectSchema() == null ? 0 : this.getObjectSchema().hashCode());
		result = 37 * result + (getObjectName() == null ? 0 : this.getObjectName().hashCode());
		result = 37 * result + (int) this.getRowsFullScanned();
		result = 37 * result + (getLatency() == null ? 0 : this.getLatency().hashCode());
		return result;
	}

}
