package com.unsw.web.entity;
// Generated 2019-10-14 18:17:54 by Hibernate Tools 5.3.10.Final

/**
 * SessionSslStatus generated by hbm2java
 */
public class SessionSslStatus implements java.io.Serializable {

	private SessionSslStatusId id;

	public SessionSslStatus() {
	}

	public SessionSslStatus(SessionSslStatusId id) {
		this.id = id;
	}

	public SessionSslStatusId getId() {
		return this.id;
	}

	public void setId(SessionSslStatusId id) {
		this.id = id;
	}

}
