package com.unsw.web.entity;
// Generated 2019-10-14 18:17:54 by Hibernate Tools 5.3.10.Final

/**
 * Session generated by hbm2java
 */
public class Session implements java.io.Serializable {

	private SessionId id;

	public Session() {
	}

	public Session(SessionId id) {
		this.id = id;
	}

	public SessionId getId() {
		return this.id;
	}

	public void setId(SessionId id) {
		this.id = id;
	}

}
