package com.unsw.web.entity;
// Generated 2019-10-14 18:17:54 by Hibernate Tools 5.3.10.Final

/**
 * StatementAnalysis generated by hbm2java
 */
public class StatementAnalysis implements java.io.Serializable {

	private StatementAnalysisId id;

	public StatementAnalysis() {
	}

	public StatementAnalysis(StatementAnalysisId id) {
		this.id = id;
	}

	public StatementAnalysisId getId() {
		return this.id;
	}

	public void setId(StatementAnalysisId id) {
		this.id = id;
	}

}
