package com.unsw.web.entity;
// Generated 2019-10-14 18:17:54 by Hibernate Tools 5.3.10.Final

/**
 * StatementsWithSorting generated by hbm2java
 */
public class StatementsWithSorting implements java.io.Serializable {

	private StatementsWithSortingId id;

	public StatementsWithSorting() {
	}

	public StatementsWithSorting(StatementsWithSortingId id) {
		this.id = id;
	}

	public StatementsWithSortingId getId() {
		return this.id;
	}

	public void setId(StatementsWithSortingId id) {
		this.id = id;
	}

}
