package com.unsw.web.entity;
// Generated 2019-10-14 18:17:54 by Hibernate Tools 5.3.10.Final

/**
 * StatementsWithTempTables generated by hbm2java
 */
public class StatementsWithTempTables implements java.io.Serializable {

	private StatementsWithTempTablesId id;

	public StatementsWithTempTables() {
	}

	public StatementsWithTempTables(StatementsWithTempTablesId id) {
		this.id = id;
	}

	public StatementsWithTempTablesId getId() {
		return this.id;
	}

	public void setId(StatementsWithTempTablesId id) {
		this.id = id;
	}

}
