package com.unsw.web.entity;
// Generated 2019-10-14 18:17:54 by Hibernate Tools 5.3.10.Final

/**
 * StatementsWithRuntimesIn95thPercentile generated by hbm2java
 */
public class StatementsWithRuntimesIn95thPercentile implements java.io.Serializable {

	private StatementsWithRuntimesIn95thPercentileId id;

	public StatementsWithRuntimesIn95thPercentile() {
	}

	public StatementsWithRuntimesIn95thPercentile(StatementsWithRuntimesIn95thPercentileId id) {
		this.id = id;
	}

	public StatementsWithRuntimesIn95thPercentileId getId() {
		return this.id;
	}

	public void setId(StatementsWithRuntimesIn95thPercentileId id) {
		this.id = id;
	}

}
