package com.unsw.web.entity;
// Generated 2019-10-14 18:17:54 by Hibernate Tools 5.3.10.Final

/**
 * UserSummaryByFileIoType generated by hbm2java
 */
public class UserSummaryByFileIoType implements java.io.Serializable {

	private UserSummaryByFileIoTypeId id;

	public UserSummaryByFileIoType() {
	}

	public UserSummaryByFileIoType(UserSummaryByFileIoTypeId id) {
		this.id = id;
	}

	public UserSummaryByFileIoTypeId getId() {
		return this.id;
	}

	public void setId(UserSummaryByFileIoTypeId id) {
		this.id = id;
	}

}
