package com.unsw.web.entity;
// Generated 2019-10-14 18:17:54 by Hibernate Tools 5.3.10.Final

/**
 * UserSummary generated by hbm2java
 */
public class UserSummary implements java.io.Serializable {

	private UserSummaryId id;

	public UserSummary() {
	}

	public UserSummary(UserSummaryId id) {
		this.id = id;
	}

	public UserSummaryId getId() {
		return this.id;
	}

	public void setId(UserSummaryId id) {
		this.id = id;
	}

}
