package com.unsw.web.entity;
// Generated 2019-10-14 18:17:54 by Hibernate Tools 5.3.10.Final

/**
 * UserSummaryByStatementLatency generated by hbm2java
 */
public class UserSummaryByStatementLatency implements java.io.Serializable {

	private UserSummaryByStatementLatencyId id;

	public UserSummaryByStatementLatency() {
	}

	public UserSummaryByStatementLatency(UserSummaryByStatementLatencyId id) {
		this.id = id;
	}

	public UserSummaryByStatementLatencyId getId() {
		return this.id;
	}

	public void setId(UserSummaryByStatementLatencyId id) {
		this.id = id;
	}

}
