package com.unsw.web.entity;
// Generated 2019-10-14 18:17:54 by Hibernate Tools 5.3.10.Final

/**
 * UserSummaryByStatementType generated by hbm2java
 */
public class UserSummaryByStatementType implements java.io.Serializable {

	private UserSummaryByStatementTypeId id;

	public UserSummaryByStatementType() {
	}

	public UserSummaryByStatementType(UserSummaryByStatementTypeId id) {
		this.id = id;
	}

	public UserSummaryByStatementTypeId getId() {
		return this.id;
	}

	public void setId(UserSummaryByStatementTypeId id) {
		this.id = id;
	}

}
