package com.unsw.web.entity;
// Generated 2019-10-14 18:17:54 by Hibernate Tools 5.3.10.Final

/**
 * WaitClassesGlobalByAvgLatency generated by hbm2java
 */
public class WaitClassesGlobalByAvgLatency implements java.io.Serializable {

	private WaitClassesGlobalByAvgLatencyId id;

	public WaitClassesGlobalByAvgLatency() {
	}

	public WaitClassesGlobalByAvgLatency(WaitClassesGlobalByAvgLatencyId id) {
		this.id = id;
	}

	public WaitClassesGlobalByAvgLatencyId getId() {
		return this.id;
	}

	public void setId(WaitClassesGlobalByAvgLatencyId id) {
		this.id = id;
	}

}
