package com.unsw.web.entity;
// Generated 2019-10-14 18:17:54 by Hibernate Tools 5.3.10.Final

/**
 * WaitsGlobalByLatency generated by hbm2java
 */
public class WaitsGlobalByLatency implements java.io.Serializable {

	private WaitsGlobalByLatencyId id;

	public WaitsGlobalByLatency() {
	}

	public WaitsGlobalByLatency(WaitsGlobalByLatencyId id) {
		this.id = id;
	}

	public WaitsGlobalByLatencyId getId() {
		return this.id;
	}

	public void setId(WaitsGlobalByLatencyId id) {
		this.id = id;
	}

}
