package com.unsw.web.entity;
// Generated 2019-10-14 18:17:54 by Hibernate Tools 5.3.10.Final

/**
 * WaitsByUserByLatency generated by hbm2java
 */
public class WaitsByUserByLatency implements java.io.Serializable {

	private WaitsByUserByLatencyId id;

	public WaitsByUserByLatency() {
	}

	public WaitsByUserByLatency(WaitsByUserByLatencyId id) {
		this.id = id;
	}

	public WaitsByUserByLatencyId getId() {
		return this.id;
	}

	public void setId(WaitsByUserByLatencyId id) {
		this.id = id;
	}

}
