package com.unsw.web.entity;
// Generated 2019-10-14 18:17:54 by Hibernate Tools 5.3.10.Final

/**
 * WaitsByHostByLatency generated by hbm2java
 */
public class WaitsByHostByLatency implements java.io.Serializable {

	private WaitsByHostByLatencyId id;

	public WaitsByHostByLatency() {
	}

	public WaitsByHostByLatency(WaitsByHostByLatencyId id) {
		this.id = id;
	}

	public WaitsByHostByLatencyId getId() {
		return this.id;
	}

	public void setId(WaitsByHostByLatencyId id) {
		this.id = id;
	}

}
