package com.unsw.web.entity;
// Generated 2019-10-14 18:17:54 by Hibernate Tools 5.3.10.Final


import com.unsw.web.entity.X.hostSummaryByFileIoId;

/**
 * X.hostSummaryByFileIo generated by hbm2java
 */
public class X.hostSummaryByFileIo  implements java.io.Serializable {


     private X.hostSummaryByFileIoId id;

    public X.hostSummaryByFileIo() {
    }

    public X.hostSummaryByFileIo(X.hostSummaryByFileIoId id) {
       this.id = id;
    }
   
    public X.hostSummaryByFileIoId getId() {
        return this.id;
    }
    
    public void setId(X.hostSummaryByFileIoId id) {
        this.id = id;
    }




}


