package com.unsw.web.entity;
// Generated 2019-10-14 18:17:54 by Hibernate Tools 5.3.10.Final


import com.unsw.web.entity.X.innodbLockWaitsId;

/**
 * X.innodbLockWaits generated by hbm2java
 */
public class X.innodbLockWaits  implements java.io.Serializable {


     private X.innodbLockWaitsId id;

    public X.innodbLockWaits() {
    }

    public X.innodbLockWaits(X.innodbLockWaitsId id) {
       this.id = id;
    }
   
    public X.innodbLockWaitsId getId() {
        return this.id;
    }
    
    public void setId(X.innodbLockWaitsId id) {
        this.id = id;
    }




}


