package com.unsw.web.entity;
// Generated 2019-10-14 18:17:54 by Hibernate Tools 5.3.10.Final


import com.unsw.web.entity.X.ioByThreadByLatencyId;

/**
 * X.ioByThreadByLatency generated by hbm2java
 */
public class X.ioByThreadByLatency  implements java.io.Serializable {


     private X.ioByThreadByLatencyId id;

    public X.ioByThreadByLatency() {
    }

    public X.ioByThreadByLatency(X.ioByThreadByLatencyId id) {
       this.id = id;
    }
   
    public X.ioByThreadByLatencyId getId() {
        return this.id;
    }
    
    public void setId(X.ioByThreadByLatencyId id) {
        this.id = id;
    }




}


