package com.unsw.web.entity;
// Generated 2019-10-14 18:17:54 by Hibernate Tools 5.3.10.Final


import com.unsw.web.entity.X.ioGlobalByFileByLatencyId;

/**
 * X.ioGlobalByFileByLatency generated by hbm2java
 */
public class X.ioGlobalByFileByLatency  implements java.io.Serializable {


     private X.ioGlobalByFileByLatencyId id;

    public X.ioGlobalByFileByLatency() {
    }

    public X.ioGlobalByFileByLatency(X.ioGlobalByFileByLatencyId id) {
       this.id = id;
    }
   
    public X.ioGlobalByFileByLatencyId getId() {
        return this.id;
    }
    
    public void setId(X.ioGlobalByFileByLatencyId id) {
        this.id = id;
    }




}


