package com.unsw.web.entity;
// Generated 2019-10-14 18:17:54 by Hibernate Tools 5.3.10.Final


import com.unsw.web.entity.X.latestFileIoId;

/**
 * X.latestFileIo generated by hbm2java
 */
public class X.latestFileIo  implements java.io.Serializable {


     private X.latestFileIoId id;

    public X.latestFileIo() {
    }

    public X.latestFileIo(X.latestFileIoId id) {
       this.id = id;
    }
   
    public X.latestFileIoId getId() {
        return this.id;
    }
    
    public void setId(X.latestFileIoId id) {
        this.id = id;
    }




}


