package com.unsw.web.entity;
// Generated 2019-10-14 18:17:54 by Hibernate Tools 5.3.10.Final


import com.unsw.web.entity.X.memoryByUserByCurrentBytesId;

/**
 * X.memoryByUserByCurrentBytes generated by hbm2java
 */
public class X.memoryByUserByCurrentBytes  implements java.io.Serializable {


     private X.memoryByUserByCurrentBytesId id;

    public X.memoryByUserByCurrentBytes() {
    }

    public X.memoryByUserByCurrentBytes(X.memoryByUserByCurrentBytesId id) {
       this.id = id;
    }
   
    public X.memoryByUserByCurrentBytesId getId() {
        return this.id;
    }
    
    public void setId(X.memoryByUserByCurrentBytesId id) {
        this.id = id;
    }




}


