package com.unsw.web.entity;
// Generated 2019-10-14 18:17:54 by Hibernate Tools 5.3.10.Final


import com.unsw.web.entity.X.psDigest95thPercentileByAvgUsId;

/**
 * X.psDigest95thPercentileByAvgUs generated by hbm2java
 */
public class X.psDigest95thPercentileByAvgUs  implements java.io.Serializable {


     private X.psDigest95thPercentileByAvgUsId id;

    public X.psDigest95thPercentileByAvgUs() {
    }

    public X.psDigest95thPercentileByAvgUs(X.psDigest95thPercentileByAvgUsId id) {
       this.id = id;
    }
   
    public X.psDigest95thPercentileByAvgUsId getId() {
        return this.id;
    }
    
    public void setId(X.psDigest95thPercentileByAvgUsId id) {
        this.id = id;
    }




}


