package com.unsw.web.entity;
// Generated 2019-10-14 18:17:54 by Hibernate Tools 5.3.10.Final


import java.math.BigDecimal;
import java.math.BigInteger;

/**
 * X.psDigest95thPercentileByAvgUsId generated by hbm2java
 */
public class X.psDigest95thPercentileByAvgUsId  implements java.io.Serializable {


     private BigInteger avgUs;
     private BigDecimal percentile;

    public X.psDigest95thPercentileByAvgUsId() {
    }

	
    public X.psDigest95thPercentileByAvgUsId(BigDecimal percentile) {
        this.percentile = percentile;
    }
    public X.psDigest95thPercentileByAvgUsId(BigInteger avgUs, BigDecimal percentile) {
       this.avgUs = avgUs;
       this.percentile = percentile;
    }
   
    public BigInteger getAvgUs() {
        return this.avgUs;
    }
    
    public void setAvgUs(BigInteger avgUs) {
        this.avgUs = avgUs;
    }
    public BigDecimal getPercentile() {
        return this.percentile;
    }
    
    public void setPercentile(BigDecimal percentile) {
        this.percentile = percentile;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof X.psDigest95thPercentileByAvgUsId) ) return false;
		 X.psDigest95thPercentileByAvgUsId castOther = ( X.psDigest95thPercentileByAvgUsId ) other; 
         
		 return ( (this.getAvgUs()==castOther.getAvgUs()) || ( this.getAvgUs()!=null && castOther.getAvgUs()!=null && this.getAvgUs().equals(castOther.getAvgUs()) ) )
 && ( (this.getPercentile()==castOther.getPercentile()) || ( this.getPercentile()!=null && castOther.getPercentile()!=null && this.getPercentile().equals(castOther.getPercentile()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getAvgUs() == null ? 0 : this.getAvgUs().hashCode() );
         result = 37 * result + ( getPercentile() == null ? 0 : this.getPercentile().hashCode() );
         return result;
   }   


}


