package com.unsw.web.entity;
// Generated 2019-10-14 18:17:54 by Hibernate Tools 5.3.10.Final


import com.unsw.web.entity.X.psSchemaTableStatisticsIoId;

/**
 * X.psSchemaTableStatisticsIo generated by hbm2java
 */
public class X.psSchemaTableStatisticsIo  implements java.io.Serializable {


     private X.psSchemaTableStatisticsIoId id;

    public X.psSchemaTableStatisticsIo() {
    }

    public X.psSchemaTableStatisticsIo(X.psSchemaTableStatisticsIoId id) {
       this.id = id;
    }
   
    public X.psSchemaTableStatisticsIoId getId() {
        return this.id;
    }
    
    public void setId(X.psSchemaTableStatisticsIoId id) {
        this.id = id;
    }




}


