package com.unsw.web.entity;
// Generated 2019-10-14 18:17:54 by Hibernate Tools 5.3.10.Final


import com.unsw.web.entity.X.schemaFlattenedKeysId;

/**
 * X.schemaFlattenedKeys generated by hbm2java
 */
public class X.schemaFlattenedKeys  implements java.io.Serializable {


     private X.schemaFlattenedKeysId id;

    public X.schemaFlattenedKeys() {
    }

    public X.schemaFlattenedKeys(X.schemaFlattenedKeysId id) {
       this.id = id;
    }
   
    public X.schemaFlattenedKeysId getId() {
        return this.id;
    }
    
    public void setId(X.schemaFlattenedKeysId id) {
        this.id = id;
    }




}


