package com.unsw.web.entity;
// Generated 2019-10-14 18:17:54 by Hibernate Tools 5.3.10.Final


import com.unsw.web.entity.X.schemaTableStatisticsWithBufferId;

/**
 * X.schemaTableStatisticsWithBuffer generated by hbm2java
 */
public class X.schemaTableStatisticsWithBuffer  implements java.io.Serializable {


     private X.schemaTableStatisticsWithBufferId id;

    public X.schemaTableStatisticsWithBuffer() {
    }

    public X.schemaTableStatisticsWithBuffer(X.schemaTableStatisticsWithBufferId id) {
       this.id = id;
    }
   
    public X.schemaTableStatisticsWithBufferId getId() {
        return this.id;
    }
    
    public void setId(X.schemaTableStatisticsWithBufferId id) {
        this.id = id;
    }




}


