package com.unsw.web.entity;
// Generated 2019-10-14 18:17:54 by Hibernate Tools 5.3.10.Final


import com.unsw.web.entity.X.statementsWithFullTableScansId;

/**
 * X.statementsWithFullTableScans generated by hbm2java
 */
public class X.statementsWithFullTableScans  implements java.io.Serializable {


     private X.statementsWithFullTableScansId id;

    public X.statementsWithFullTableScans() {
    }

    public X.statementsWithFullTableScans(X.statementsWithFullTableScansId id) {
       this.id = id;
    }
   
    public X.statementsWithFullTableScansId getId() {
        return this.id;
    }
    
    public void setId(X.statementsWithFullTableScansId id) {
        this.id = id;
    }




}


