package com.unsw.web.entity;
// Generated 2019-10-14 18:17:54 by Hibernate Tools 5.3.10.Final


import com.unsw.web.entity.X.statementAnalysisId;

/**
 * X.statementAnalysis generated by hbm2java
 */
public class X.statementAnalysis  implements java.io.Serializable {


     private X.statementAnalysisId id;

    public X.statementAnalysis() {
    }

    public X.statementAnalysis(X.statementAnalysisId id) {
       this.id = id;
    }
   
    public X.statementAnalysisId getId() {
        return this.id;
    }
    
    public void setId(X.statementAnalysisId id) {
        this.id = id;
    }




}


