package com.unsw.web.entity;
// Generated 2019-10-14 18:17:54 by Hibernate Tools 5.3.10.Final


import com.unsw.web.entity.X.statementsWithErrorsOrWarningsId;

/**
 * X.statementsWithErrorsOrWarnings generated by hbm2java
 */
public class X.statementsWithErrorsOrWarnings  implements java.io.Serializable {


     private X.statementsWithErrorsOrWarningsId id;

    public X.statementsWithErrorsOrWarnings() {
    }

    public X.statementsWithErrorsOrWarnings(X.statementsWithErrorsOrWarningsId id) {
       this.id = id;
    }
   
    public X.statementsWithErrorsOrWarningsId getId() {
        return this.id;
    }
    
    public void setId(X.statementsWithErrorsOrWarningsId id) {
        this.id = id;
    }




}


