package com.unsw.web.entity;
// Generated 2019-10-14 18:17:54 by Hibernate Tools 5.3.10.Final


import java.math.BigInteger;
import java.util.Date;

/**
 * X.statementsWithFullTableScansId generated by hbm2java
 */
public class X.statementsWithFullTableScansId  implements java.io.Serializable {


     private String query;
     private String db;
     private long execCount;
     private long totalLatency;
     private long noIndexUsedCount;
     private long noGoodIndexUsedCount;
     private BigInteger noIndexUsedPct;
     private long rowsSent;
     private long rowsExamined;
     private BigInteger rowsSentAvg;
     private BigInteger rowsExaminedAvg;
     private Date firstSeen;
     private Date lastSeen;
     private String digest;

    public X.statementsWithFullTableScansId() {
    }

	
    public X.statementsWithFullTableScansId(long execCount, long totalLatency, long noIndexUsedCount, long noGoodIndexUsedCount, BigInteger noIndexUsedPct, long rowsSent, long rowsExamined, Date firstSeen, Date lastSeen) {
        this.execCount = execCount;
        this.totalLatency = totalLatency;
        this.noIndexUsedCount = noIndexUsedCount;
        this.noGoodIndexUsedCount = noGoodIndexUsedCount;
        this.noIndexUsedPct = noIndexUsedPct;
        this.rowsSent = rowsSent;
        this.rowsExamined = rowsExamined;
        this.firstSeen = firstSeen;
        this.lastSeen = lastSeen;
    }
    public X.statementsWithFullTableScansId(String query, String db, long execCount, long totalLatency, long noIndexUsedCount, long noGoodIndexUsedCount, BigInteger noIndexUsedPct, long rowsSent, long rowsExamined, BigInteger rowsSentAvg, BigInteger rowsExaminedAvg, Date firstSeen, Date lastSeen, String digest) {
       this.query = query;
       this.db = db;
       this.execCount = execCount;
       this.totalLatency = totalLatency;
       this.noIndexUsedCount = noIndexUsedCount;
       this.noGoodIndexUsedCount = noGoodIndexUsedCount;
       this.noIndexUsedPct = noIndexUsedPct;
       this.rowsSent = rowsSent;
       this.rowsExamined = rowsExamined;
       this.rowsSentAvg = rowsSentAvg;
       this.rowsExaminedAvg = rowsExaminedAvg;
       this.firstSeen = firstSeen;
       this.lastSeen = lastSeen;
       this.digest = digest;
    }
   
    public String getQuery() {
        return this.query;
    }
    
    public void setQuery(String query) {
        this.query = query;
    }
    public String getDb() {
        return this.db;
    }
    
    public void setDb(String db) {
        this.db = db;
    }
    public long getExecCount() {
        return this.execCount;
    }
    
    public void setExecCount(long execCount) {
        this.execCount = execCount;
    }
    public long getTotalLatency() {
        return this.totalLatency;
    }
    
    public void setTotalLatency(long totalLatency) {
        this.totalLatency = totalLatency;
    }
    public long getNoIndexUsedCount() {
        return this.noIndexUsedCount;
    }
    
    public void setNoIndexUsedCount(long noIndexUsedCount) {
        this.noIndexUsedCount = noIndexUsedCount;
    }
    public long getNoGoodIndexUsedCount() {
        return this.noGoodIndexUsedCount;
    }
    
    public void setNoGoodIndexUsedCount(long noGoodIndexUsedCount) {
        this.noGoodIndexUsedCount = noGoodIndexUsedCount;
    }
    public BigInteger getNoIndexUsedPct() {
        return this.noIndexUsedPct;
    }
    
    public void setNoIndexUsedPct(BigInteger noIndexUsedPct) {
        this.noIndexUsedPct = noIndexUsedPct;
    }
    public long getRowsSent() {
        return this.rowsSent;
    }
    
    public void setRowsSent(long rowsSent) {
        this.rowsSent = rowsSent;
    }
    public long getRowsExamined() {
        return this.rowsExamined;
    }
    
    public void setRowsExamined(long rowsExamined) {
        this.rowsExamined = rowsExamined;
    }
    public BigInteger getRowsSentAvg() {
        return this.rowsSentAvg;
    }
    
    public void setRowsSentAvg(BigInteger rowsSentAvg) {
        this.rowsSentAvg = rowsSentAvg;
    }
    public BigInteger getRowsExaminedAvg() {
        return this.rowsExaminedAvg;
    }
    
    public void setRowsExaminedAvg(BigInteger rowsExaminedAvg) {
        this.rowsExaminedAvg = rowsExaminedAvg;
    }
    public Date getFirstSeen() {
        return this.firstSeen;
    }
    
    public void setFirstSeen(Date firstSeen) {
        this.firstSeen = firstSeen;
    }
    public Date getLastSeen() {
        return this.lastSeen;
    }
    
    public void setLastSeen(Date lastSeen) {
        this.lastSeen = lastSeen;
    }
    public String getDigest() {
        return this.digest;
    }
    
    public void setDigest(String digest) {
        this.digest = digest;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof X.statementsWithFullTableScansId) ) return false;
		 X.statementsWithFullTableScansId castOther = ( X.statementsWithFullTableScansId ) other; 
         
		 return ( (this.getQuery()==castOther.getQuery()) || ( this.getQuery()!=null && castOther.getQuery()!=null && this.getQuery().equals(castOther.getQuery()) ) )
 && ( (this.getDb()==castOther.getDb()) || ( this.getDb()!=null && castOther.getDb()!=null && this.getDb().equals(castOther.getDb()) ) )
 && (this.getExecCount()==castOther.getExecCount())
 && (this.getTotalLatency()==castOther.getTotalLatency())
 && (this.getNoIndexUsedCount()==castOther.getNoIndexUsedCount())
 && (this.getNoGoodIndexUsedCount()==castOther.getNoGoodIndexUsedCount())
 && ( (this.getNoIndexUsedPct()==castOther.getNoIndexUsedPct()) || ( this.getNoIndexUsedPct()!=null && castOther.getNoIndexUsedPct()!=null && this.getNoIndexUsedPct().equals(castOther.getNoIndexUsedPct()) ) )
 && (this.getRowsSent()==castOther.getRowsSent())
 && (this.getRowsExamined()==castOther.getRowsExamined())
 && ( (this.getRowsSentAvg()==castOther.getRowsSentAvg()) || ( this.getRowsSentAvg()!=null && castOther.getRowsSentAvg()!=null && this.getRowsSentAvg().equals(castOther.getRowsSentAvg()) ) )
 && ( (this.getRowsExaminedAvg()==castOther.getRowsExaminedAvg()) || ( this.getRowsExaminedAvg()!=null && castOther.getRowsExaminedAvg()!=null && this.getRowsExaminedAvg().equals(castOther.getRowsExaminedAvg()) ) )
 && ( (this.getFirstSeen()==castOther.getFirstSeen()) || ( this.getFirstSeen()!=null && castOther.getFirstSeen()!=null && this.getFirstSeen().equals(castOther.getFirstSeen()) ) )
 && ( (this.getLastSeen()==castOther.getLastSeen()) || ( this.getLastSeen()!=null && castOther.getLastSeen()!=null && this.getLastSeen().equals(castOther.getLastSeen()) ) )
 && ( (this.getDigest()==castOther.getDigest()) || ( this.getDigest()!=null && castOther.getDigest()!=null && this.getDigest().equals(castOther.getDigest()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getQuery() == null ? 0 : this.getQuery().hashCode() );
         result = 37 * result + ( getDb() == null ? 0 : this.getDb().hashCode() );
         result = 37 * result + (int) this.getExecCount();
         result = 37 * result + (int) this.getTotalLatency();
         result = 37 * result + (int) this.getNoIndexUsedCount();
         result = 37 * result + (int) this.getNoGoodIndexUsedCount();
         result = 37 * result + ( getNoIndexUsedPct() == null ? 0 : this.getNoIndexUsedPct().hashCode() );
         result = 37 * result + (int) this.getRowsSent();
         result = 37 * result + (int) this.getRowsExamined();
         result = 37 * result + ( getRowsSentAvg() == null ? 0 : this.getRowsSentAvg().hashCode() );
         result = 37 * result + ( getRowsExaminedAvg() == null ? 0 : this.getRowsExaminedAvg().hashCode() );
         result = 37 * result + ( getFirstSeen() == null ? 0 : this.getFirstSeen().hashCode() );
         result = 37 * result + ( getLastSeen() == null ? 0 : this.getLastSeen().hashCode() );
         result = 37 * result + ( getDigest() == null ? 0 : this.getDigest().hashCode() );
         return result;
   }   


}


