package com.unsw.web.entity;
// Generated 2019-10-14 18:17:54 by Hibernate Tools 5.3.10.Final


import com.unsw.web.entity.X.statementsWithRuntimesIn95thPercentileId;

/**
 * X.statementsWithRuntimesIn95thPercentile generated by hbm2java
 */
public class X.statementsWithRuntimesIn95thPercentile  implements java.io.Serializable {


     private X.statementsWithRuntimesIn95thPercentileId id;

    public X.statementsWithRuntimesIn95thPercentile() {
    }

    public X.statementsWithRuntimesIn95thPercentile(X.statementsWithRuntimesIn95thPercentileId id) {
       this.id = id;
    }
   
    public X.statementsWithRuntimesIn95thPercentileId getId() {
        return this.id;
    }
    
    public void setId(X.statementsWithRuntimesIn95thPercentileId id) {
        this.id = id;
    }




}


