package com.unsw.web.entity;
// Generated 2019-10-14 18:17:54 by Hibernate Tools 5.3.10.Final


import com.unsw.web.entity.X.userSummaryId;

/**
 * X.userSummary generated by hbm2java
 */
public class X.userSummary  implements java.io.Serializable {


     private X.userSummaryId id;

    public X.userSummary() {
    }

    public X.userSummary(X.userSummaryId id) {
       this.id = id;
    }
   
    public X.userSummaryId getId() {
        return this.id;
    }
    
    public void setId(X.userSummaryId id) {
        this.id = id;
    }




}


