package com.unsw.web.entity;
// Generated 2019-10-14 18:17:54 by Hibernate Tools 5.3.10.Final


import com.unsw.web.entity.X.userSummaryByStagesId;

/**
 * X.userSummaryByStages generated by hbm2java
 */
public class X.userSummaryByStages  implements java.io.Serializable {


     private X.userSummaryByStagesId id;

    public X.userSummaryByStages() {
    }

    public X.userSummaryByStages(X.userSummaryByStagesId id) {
       this.id = id;
    }
   
    public X.userSummaryByStagesId getId() {
        return this.id;
    }
    
    public void setId(X.userSummaryByStagesId id) {
        this.id = id;
    }




}


