package com.unsw.web.entity;
// Generated 2019-10-14 18:17:54 by Hibernate Tools 5.3.10.Final


import com.unsw.web.entity.X.waitClassesGlobalByLatencyId;

/**
 * X.waitClassesGlobalByLatency generated by hbm2java
 */
public class X.waitClassesGlobalByLatency  implements java.io.Serializable {


     private X.waitClassesGlobalByLatencyId id;

    public X.waitClassesGlobalByLatency() {
    }

    public X.waitClassesGlobalByLatency(X.waitClassesGlobalByLatencyId id) {
       this.id = id;
    }
   
    public X.waitClassesGlobalByLatencyId getId() {
        return this.id;
    }
    
    public void setId(X.waitClassesGlobalByLatencyId id) {
        this.id = id;
    }




}


