package com.unsw.web.mealReco.entity;
// Generated 2019-10-18 17:39:37 by Hibernate Tools 5.2.12.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Recipe generated by hbm2java
 */
@Entity
@Table(name = "recipe", catalog = "mymeal", uniqueConstraints = @UniqueConstraint(columnNames = "label"))
public class Recipe implements java.io.Serializable {

	private Integer recipeId;
	private long calories;
	private String carbs;
	private int categoryId;
	private String description;
	private String dishType;
	private long fat;
	private String image;
	private String label;
	private Date lastUpdateTime;
	private String mealType;
	private long protein;
	private Date publishDate;
	private long sugar;

	public Recipe() {
	}

	public Recipe(long calories, String carbs, int categoryId, String description, String dishType, long fat,
			String image, String label, Date lastUpdateTime, String mealType, long protein, Date publishDate,
			long sugar) {
		this.calories = calories;
		this.carbs = carbs;
		this.categoryId = categoryId;
		this.description = description;
		this.dishType = dishType;
		this.fat = fat;
		this.image = image;
		this.label = label;
		this.lastUpdateTime = lastUpdateTime;
		this.mealType = mealType;
		this.protein = protein;
		this.publishDate = publishDate;
		this.sugar = sugar;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "recipe_id", unique = true, nullable = false)
	public Integer getRecipeId() {
		return this.recipeId;
	}

	public void setRecipeId(Integer recipeId) {
		this.recipeId = recipeId;
	}

	@Column(name = "calories", nullable = false, precision = 10, scale = 0)
	public long getCalories() {
		return this.calories;
	}

	public void setCalories(long calories) {
		this.calories = calories;
	}

	@Column(name = "carbs", nullable = false, length = 10)
	public String getCarbs() {
		return this.carbs;
	}

	public void setCarbs(String carbs) {
		this.carbs = carbs;
	}

	@Column(name = "category_id", nullable = false)
	public int getCategoryId() {
		return this.categoryId;
	}

	public void setCategoryId(int categoryId) {
		this.categoryId = categoryId;
	}

	@Column(name = "description", nullable = false)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "dish_type", nullable = false, length = 100)
	public String getDishType() {
		return this.dishType;
	}

	public void setDishType(String dishType) {
		this.dishType = dishType;
	}

	@Column(name = "fat", nullable = false, precision = 10, scale = 0)
	public long getFat() {
		return this.fat;
	}

	public void setFat(long fat) {
		this.fat = fat;
	}

	@Column(name = "image", nullable = false, length = 1000)
	public String getImage() {
		return this.image;
	}

	public void setImage(String image) {
		this.image = image;
	}

	@Column(name = "label", unique = true, nullable = false, length = 128)
	public String getLabel() {
		return this.label;
	}

	public void setLabel(String label) {
		this.label = label;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "last_update_time", nullable = false, length = 19)
	public Date getLastUpdateTime() {
		return this.lastUpdateTime;
	}

	public void setLastUpdateTime(Date lastUpdateTime) {
		this.lastUpdateTime = lastUpdateTime;
	}

	@Column(name = "meal_type", nullable = false, length = 100)
	public String getMealType() {
		return this.mealType;
	}

	public void setMealType(String mealType) {
		this.mealType = mealType;
	}

	@Column(name = "protein", nullable = false, precision = 10, scale = 0)
	public long getProtein() {
		return this.protein;
	}

	public void setProtein(long protein) {
		this.protein = protein;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "publish_date", nullable = false, length = 10)
	public Date getPublishDate() {
		return this.publishDate;
	}

	public void setPublishDate(Date publishDate) {
		this.publishDate = publishDate;
	}

	@Column(name = "sugar", nullable = false, precision = 10, scale = 0)
	public long getSugar() {
		return this.sugar;
	}

	public void setSugar(long sugar) {
		this.sugar = sugar;
	}

}
